global:
  slack_api_url: ''

route:
  receiver: 'warning'

  routes:
    - match:
        severity: warning
      receiver: warning

    - match:
        severity: critical
      receiver: critical

receivers:
  - name: 'warning'
    slack_configs:
      - channel: '#random'
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

  - name: 'critical'
    slack_configs:
      - channel: '#general'
        text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"