services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    ports:
      - "5601:5601"
    links:
      - "elastic:elasticsearch"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/provisioning/:/etc/grafana/provisioning/"
