groups:
  - name: alert.rules

    rules:
    - alert: WorkshopExampleAppIsDown
      expr: up == 0
      for: 20s
      labels:
        severity: page
      annotations:
        summary: "Instance {{ $labels.instance }} is down."
        description: "Instance {{ $labels.instance }} of job {{ $labels.job }} has not been providing any metrics for 20 seconds."